### ISSUE TITLE
Enable Windows build

### ISSUE THREAD

**Issue by lannybroo** [conda-forge/pycapnp-feedstock#7]
As of sandstorm-io/capnproto#396, the full (not LITE) capnproto builds with Visual Studio. So perhaps we should try to get conda-forge binaries working for Windows.

**Comment by frol** [comment]
I have no experience with Windows build tools, and I don't have a Windows machine anywhere near, so I won't be able to produce the build. PRs are very welcome, though!

**Comment by harrishancock** [comment]
FYI, I looked into building pycapnp with VS2015 a while ago and I seem to recall that pycapnp requires dynamic schema parsing. (Perhaps @jparyani can confirm.) While capnproto builds with VS2015, it cannot parse schemas yet, so it's not quite "full" and I expect a little more C++ porting work is required before pycapnp will build with MSVC.
